index:
    path: /
    defaults: { _controller: 'App\Controller\PersonController::index' }

newPerson:
    path: /person/new
    defaults: { _controller: 'App\Controller\PersonController::newPerson' }

newMaterial:
    path: /material/new
    defaults: { _controller: 'App\Controller\MaterialController::newMaterial' }

# first, run composer req annotations
#controllers:
#    resource: ../src/Controller/
#    type: annotation
